layout_spectrum: 1
typography_spectrum: 1
color:
  lightness: 0.1863406
  brandStrength: 0.8541315
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Testing 123456789
